--- # checking vars
 - hosts: dev
   user: ansible
   become: yes
   connection: ssh
   vars:
           pkgname: httpd
   tasks:
           - name: creating users in servers
             user: name='{{item}}' state=present
             with_items:
                     - raj
                     - mohan
                     - devendra
                     - bhupindra

             
