--- # MYSQL server installation

- hosts: com
  user: ansible
  become: yes
  tasks:
          - name: Install WGET
            yum:
                 name: wget 
                 state: installed
            
          - name: Install MySQL-python
            yum:
                 name: python3-PyMySQL
                 state: present

          - name: MySQL Directory creation in progress at usr
            file:
                    path: /usr/mysql
                    state: directory
                    mode: 0755
         
          - name: Download rpm lib for MySQL
            get_url:
                    url: "https://repo.mysql.com//mysql80-community-release-el8-1.noarch.rpm"
                    dest: /usr/mysql/
         
          - name: Install MYSQL rpm
            yum: 
                name: /usr/mysql/mysql80-community-release-el8-1.noarch.rpm 
                state: present
                disable_gpg_check: True

         
          - name: Update Package
            yum: 
                name: mysql-server
                state: latest 
              
         
          - name: Verifying MySQL Installation 
            yum:
                 name: mysql-server 
                 state: installed
         
          - name: Start MYSQL service
            service:
                    name: mysqld 
                    state: restarted
         
          - name: Create .my.cnf file with root password credentials
            become: yes
            template: src=".my.cnf.j2" dest="/root/.my.cnf" owner=root group=root mode=0600 
         
          - name: Create user mysql
            # no_log: true
            mysql_user: 
                    name: root
                    host: localhost
                    password: mysql
                    login_user: root
                    check_implicit_admin: yes
                    priv: "*.*:ALL,GRANT" 
                    state: present
                    

          - name: Create database comcast
            mysql_db:
                    # login_unix_socket: /var/lib/mysql/mysql.sock
                    name: comcast
                    login_user: root
                    login_password: mysql
                    state: present
                    login_unix_socket: /var/lib/mysql/mysql.sock


          - name: assign user access
            mysql_db:
                    name: comcast
                    login_user: mysql
                    login_password: root123
                    state: present
         
          - name: Restart mysql
            service: 
                    name: mysqld 
                    state: restarted

          - name: Copying the dump sql file to target 
            copy: src=dump.sql dest=/tmp/dump.sql  

          - name: Creating a sample table to database comcast comcastinterview  
            mysql_db: name=comcast state=import target=/tmp/dump.sql login_user=root login_password=mysql

           

       

